### ISSUE TITLE
Define the content of the packet sent in the deploy phase

### ISSUE THREAD

**Issue by simonedavico** [benchflow/experiments-manager#27]
We should formally define and discuss the contents of the package sent in the deploy phase.

As of today, the benchmark should contain:
1. `docker-compose.yml`, the deployment descriptor for the sut;
2. `benchflow-benchmark.yml`, the benchmark configuration file;
3. `models/`, a directory containing models for the workflow management system.

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#210
