### ISSUE TITLE
Definition of the status for experiments and trials

### ISSUE THREAD

**Issue by simonedavico** [benchflow/experiments-manager#33]
Regarding the status of the experiment:
- It is possible to retrieve the status of a single trial (which may be `QUEUED`, `RUNNING`, `COMPLETED` or `FAILED`);

Example:

``` json
{ 
    "trialId": "fooBenchmark.1.1", 
    "status": "COMPLETED" 
}
```
- It is possible to retrieve the aggregated status of an experiment (which may be `RUNNING` or `COMPLETED`), which also reports the status of the single trials. 

Example:

``` json
{
    "experimentId": "fooBenchmark.1",
    "status": "RUNNING",
    "trials": [
         { "trialId": "fooBenchmark.1.1", "status": "COMPLETED" },
         { "trialId": "fooBenchmark.1.2", "status": "RUNNING" }
    ]
}
```

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#214
