### ISSUE TITLE
Switch to mainstream version of commons minio client

### ISSUE THREAD

**Issue by simonedavico** [benchflow/experiments-manager#41]
Currently the `experiments-manager` relies on [the v-dev release of my personal fork of benchflow-commons](https://github.com/simonedavico/commons/releases/v-dev) to retrieve the java minio client.

We should switch as soon as possible to the dependency from the release of the mainstream repository.

Related also to [this issue of drivers-maker](http://github.com/benchflow/drivers-maker/issues/54).

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#218
