### ISSUE TITLE
Queue for managing multiple experiments

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/experiments-manager#47]
@VincenzoFerme, from what I can see currently all experiments (they are for some reason called tests in (parts of) the code(?)) are put in a thread pool, and then all trials are executed in parallel until they have completed. After the experiment has been submitted it is then possible to get the status of the experiment and individual trials.

**_Discussion_**: Currently we rely on Faban's internal queue to schedule trials. We would like to have more control so therefore we want to add a queue (see screenshot). Some functionality in the EM will be moved to a new component called Faban Manager.

<img width="1083" alt="screen shot 2016-10-04 at 11 53 42" src="https://cloud.githubusercontent.com/assets/8646217/19069908/3ec1436c-8a29-11e6-83c0-1c965515e1d3.png">

If I understand correctly the BenchFlow-Client submits the experiments to the Experiments-Manager. It seems though that they currently are not aligned since for instance there is no `/deploy` API call on EM. Also all calls from the client to EM is done by polling.

**_Discussion_**: Yes, they are currently not aligned. By introducing Faban Manager and event bus we can avoid polling. A new client will be implemented.

I suggest to first work out a sequence diagram of how we want the interaction to happen when we add the queue, and then based on that make the architecture for EM. We can then already in this include the test orchestrator. 

**_Discussion_**: (see photo)

![img_1351](https://cloud.githubusercontent.com/assets/8646217/19071576/1c38323a-8a31-11e6-84ed-cef07a50e0bc.png)

I think it would also be nice to notify the caller when an experiment has finished, specially since we would like to be able to make decisions regarding space exploration.

**_Discussion_**: Notification will be done through Faban Manager and the event bus.

Could you please also clarify to me what is the difference between test and experiment in the context of BenchFlow? To me it seems they are mixed a bit.

**_Discussion_**: Tests consists of experiments. Experiments consists of trials.

**Comment by VincenzoFerme** [comment]
Given that we are going to rework this service, lets start to add test in CI in a structured way. Some references:

- A complete overview video on the test possibilities: https://www.youtube.com/watch?v=RX_pGTuKdFQ
- Simplified, official documentation by Dropwizard: http://www.dropwizard.io/0.7.1/docs/manual/testing.html
- A more detailed version of the previous guide, mainly about the testing part: https://nbsoftsolutions.com/blog/getting-started-with-dropwizard-testing.html
- An interesting approach with tools proposal: https://blog.logentries.com/2014/06/smart-integration-testing/
- Another approach with tools: https://intentmedia.com/testing-a-dropwizard-application-with-cucumber-jvm/

**Comment by jeppe-style** [comment]
(in progress)
Test Tools
* Unit Test
  * testng
  * JUnit
* Code Coverage
  * jacobo
  * cobertura
* Style
  * Checkstyle
* Mutation test
  * pitest

**Comment by VincenzoFerme** [comment]
@jeppe-style can you move you comment in https://github.com/benchflow/benchflow/issues/27, and delete from this issue, please?

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#222
