### ISSUE TITLE
Unable to access local minio instance through the minio-java library

### ISSUE THREAD

**Issue by simonedavico** [benchflow/experiments-manager#5]
See minio/minio-java#289.

**Comment by simonedavico** [comment]
The original issue was closed; the author advised using a previous version of the library to work with minio's Docker image, since the image has not been updated to account for some recent changes (more details in the original issue). 

Should we keep this open?

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#200
